# Generated by Django 5.0.14 on 2026-08-31 14:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ClickEvent",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "clicked_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        help_text="Timestamp when the redirect occurred",
                    ),
                ),
                (
                    "ip_hash",
                    models.CharField(
                        db_index=True,
                        help_text="SHA-256 salted hash of IP address for GDPR-compliant unique visitor tracking",
                        max_length=64,
                    ),
                ),
                (
                    "country_code",
                    models.CharField(
                        db_index=True,
                        default="US",
                        help_text="ISO 3166-1 alpha-2 country code",
                        max_length=4,
                    ),
                ),
                (
                    "city",
                    models.CharField(blank=True, default="Unknown", max_length=100),
                ),
                (
                    "browser",
                    models.CharField(blank=True, default="Unknown", max_length=64),
                ),
                ("os", models.CharField(blank=True, default="Unknown", max_length=64)),
                (
                    "device_type",
                    models.CharField(db_index=True, default="Desktop", max_length=32),
                ),
                ("is_bot", models.BooleanField(default=False)),
                (
                    "referrer",
                    models.CharField(blank=True, default="Direct", max_length=2048),
                ),
            ],
            options={
                "db_table": "link_click_events",
                "ordering": ["-clicked_at"],
            },
        ),
        migrations.CreateModel(
            name="DailyLinkMetrics",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("date", models.DateField(db_index=True)),
                ("total_clicks", models.PositiveIntegerField(default=0)),
                ("unique_visitors", models.PositiveIntegerField(default=0)),
                ("top_countries", models.JSONField(default=dict)),
                ("top_browsers", models.JSONField(default=dict)),
                ("top_devices", models.JSONField(default=dict)),
                ("top_referrers", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "daily_link_metrics",
            },
        ),
    ]
