# Generated by Django 5.0.14 on 2026-08-31 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("analytics", "0001_initial"),
        ("links", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="clickevent",
            name="link",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="click_events",
                to="links.link",
            ),
        ),
        migrations.AddField(
            model_name="dailylinkmetrics",
            name="link",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="daily_metrics",
                to="links.link",
            ),
        ),
        migrations.AddIndex(
            model_name="clickevent",
            index=models.Index(
                fields=["link", "-clicked_at"], name="idx_click_link_time"
            ),
        ),
        migrations.AddIndex(
            model_name="clickevent",
            index=models.Index(
                fields=["clicked_at", "link"], name="idx_click_time_link"
            ),
        ),
        migrations.AddIndex(
            model_name="dailylinkmetrics",
            index=models.Index(fields=["link", "-date"], name="idx_daily_link_date"),
        ),
        migrations.AddConstraint(
            model_name="dailylinkmetrics",
            constraint=models.UniqueConstraint(
                fields=("link", "date"), name="unique_daily_link_metric"
            ),
        ),
    ]
