# Generated by Django 5.0.14 on 2026-08-31 14:22

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Link",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "short_code",
                    models.CharField(
                        db_index=True,
                        help_text="Unique Base62 short code or custom alias",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "custom_alias",
                    models.CharField(
                        blank=True,
                        help_text="User specified custom alias if provided",
                        max_length=64,
                        null=True,
                    ),
                ),
                (
                    "original_url",
                    models.TextField(help_text="Original long destination URL"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Soft disable/enable toggle for the link",
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Optional expiration timestamp",
                        null=True,
                    ),
                ),
                (
                    "click_count",
                    models.BigIntegerField(
                        default=0, help_text="Cached total click count"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "links",
                "ordering": ["-created_at"],
            },
        ),
    ]
