# Generated by Django 5.0.14 on 2026-08-31 14:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("links", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="link",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="links",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="link",
            index=models.Index(
                fields=["user", "-created_at"], name="idx_link_user_created"
            ),
        ),
        migrations.AddIndex(
            model_name="link",
            index=models.Index(
                fields=["is_active", "expires_at"], name="idx_link_active_expires"
            ),
        ),
    ]
